name: Build/release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Archive
        run: tar --exclude=".+" --exclude="deploy.tar.gz" -czvf deploy.tar.gz -C . *

      - name: Release
        run: 'curl --fail -X POST -H "Authorization: Bearer ${{ secrets.DEPLOY }}" -F "upload=@deploy.tar.gz" "https://sites.1f349.com/u?site=ktane-icons.mrmelon54.com&branch=${{ github.ref_name }}"'
